# Generated by Django 4.0.5 on 2022-06-23 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='envio_pedido',
            fields=[
                ('id_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_envio', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='estado_pedido',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=75)),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('fec_publi', models.DateField()),
                ('imagen', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_vendedor', models.BooleanField(default=False, verbose_name='Quieres ser vendedor?')),
                ('direccion', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=75)),
                ('tar_cred', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='imagen_prod',
            fields=[
                ('id_img', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imgs_producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='det_pedido',
            fields=[
                ('id_det_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_produ', models.IntegerField()),
                ('total_prec', models.IntegerField()),
                ('pedido', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_carr', models.IntegerField(primary_key=True, serialize=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.persona')),
            ],
        ),
    ]
