# Generated by Django 4.0.5 on 2022-06-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_persona_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_carrito',
            fields=[
                ('id_prod_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.producto')),
            ],
        ),
    ]
